global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'my_pipeline'
    metrics_path: /metrics
    static_configs:
    - targets:
        - pipeline:8080

        